
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");

canvas.width = 520;
canvas.height = 220;

// ================= STATE =================
let running = false;
let x = 0;

let signal = [];
let bpm = 0;
let lastPeak = Date.now();

let currentState = "NORMAL";

// ================= SIMPLE BEEP SOUND =================
// THIS ALWAYS WORKS (NO FILES NEEDED)
let audioCtx = null;

function beep(state) {

    if (!audioCtx) {
        audioCtx = new (window.AudioContext || window.webkitAudioContext)();
    }

    let freq = 600;

    if (state === "WARNING") freq = 900;
    if (state === "CRITICAL") freq = 1200;

    let osc = audioCtx.createOscillator();
    let gain = audioCtx.createGain();

    osc.type = "sine";
    osc.frequency.value = freq;

    gain.gain.value = 0.08;

    osc.connect(gain);
    gain.connect(audioCtx.destination);

    osc.start();
    osc.stop(audioCtx.currentTime + 0.12);
}

// ================= ECG =================
function ecg(i) {

    let cycle = i % 100;
    let value = Math.random() * 5;

    if (cycle < 10) value = 10;
    else if (cycle < 20) value = -8;

    else if (cycle < 30) {

        value = 80;

        let now = Date.now();
        let diff = now - lastPeak;

        if (diff > 300 && diff < 2000) {
            bpm = Math.round(60000 / diff);
        }

        lastPeak = now;
    }

    else if (cycle < 40) value = -10;
    else value = 20;

    return value;
}

// ================= RISK =================
function riskIndex(bpm) {

    if (!bpm) return 0;

    let score = 0;

    if (bpm < 60) score += 40;
    if (bpm > 100) score += 40;
    if (bpm < 40 || bpm > 130) score += 30;

    return Math.min(100, score);
}

// ================= ALARM =================
function alarmState(bpm) {

    if (!bpm) return "NORMAL";

    if (bpm < 40 || bpm > 130) return "CRITICAL";
    if (bpm < 60 || bpm > 100) return "WARNING";

    return "NORMAL";
}

// ================= DRAW =================
function draw() {

    if (!running) return;

    ctx.fillStyle = "black";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    let value = ecg(x);
    signal.push(value);

    if (signal.length > canvas.width) signal.shift();

    ctx.beginPath();
    ctx.strokeStyle = "#00ff66";

    for (let i = 0; i < signal.length; i++) {
        ctx.lineTo(i, canvas.height / 2 - signal[i]);
    }

    ctx.stroke();

    x++;

    let risk = riskIndex(bpm);
    let alarm = alarmState(bpm);

    document.getElementById("bpm").innerText = "BPM: " + (bpm || "--");
    document.getElementById("risk").innerText = "Risk Index: " + risk;
    document.getElementById("alarm").innerText = "Alarm: " + alarm;

    // ================= STABLE SOUND CONTROL =================
    if (alarm !== currentState) {
        currentState = alarm;
        beep(alarm);
    }

    requestAnimationFrame(draw);
}

// ================= CONTROLS =================
function toggle() {

    running = !running;

    if (running) {
        if (!audioCtx) {
            audioCtx = new (window.AudioContext || window.webkitAudioContext)();
        }
        draw();
    }
}

// ================= PDF EXPORT (FULL FIXED DETAILS) =================
function exportPDF() {

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    let risk = riskIndex(bpm);
    let alarm = alarmState(bpm);

    let now = new Date();

    // HEADER
    doc.setFontSize(16);
    doc.text("HOSPITAL ECG BIOMEDICAL REPORT", 20, 20);

    // PATIENT DETAILS
    doc.setFontSize(11);
    doc.text("Patient Name: xxxxxxxxxxxxxxxxx", 20, 40);
    doc.text("Hospital Name: xxxxxxxxxxxxxxxxx", 20, 50);
    doc.text("Medical Doctor: xxxxxxxxxxxxxxxxx", 20, 60);
    doc.text("Biomedical Technician: xxxxxxxxxxxxx", 20, 70);

    doc.text("Department: ICU", 20, 85);
    doc.text("Bed Number: xxxx", 20, 95);

    // VITALS
    doc.text("Heart Rate (BPM): " + (bpm || "N/A"), 20, 110);
    doc.text("Risk Index: " + risk + "/100", 20, 120);
    doc.text("Condition: " + alarm, 20, 130);

    // ACTION
    let action =
        alarm === "NORMAL"
            ? "Patient stable. Continue monitoring."
            : alarm === "WARNING"
            ? "Abnormal signs detected. Increase monitoring."
            : "CRITICAL CONDITION: Immediate ICU intervention required.";

    doc.text("Immediate Action: " + action, 20, 150);

    // TIME INFO
    doc.text("Date: " + now.toLocaleDateString(), 20, 170);
    doc.text("Time: " + now.toLocaleTimeString(), 20, 180);

    doc.text("Generated by ECG Biomedical Analyzer System", 20, 200);

    doc.save("ECG_Patient_Report.pdf");
}
