
const canvas = document.getElementById("canvas");
const ctx = canvas.getContext("2d");

const spec = document.getElementById("spectrum");
const sctx = spec ? spec.getContext("2d") : null;

canvas.width = 520;
canvas.height = 220;

if (spec) {
    spec.width = 520;
    spec.height = 120;
}

// ================= STATE =================
let running = false;
let x = 0;

let signal = [];
let bpm = 0;
let lastPeak = Date.now();

let history = [];

// alarm stability (1 minute rule)
let lastStableAlarm = "NORMAL";
let changeCounter = 0;

// ================= AUDIO (RINGTONE STYLE) =================
let audioCtx = new (window.AudioContext || window.webkitAudioContext)();

let alarmInterval = null;

function playTone(freq) {

    let osc = audioCtx.createOscillator();
    let gain = audioCtx.createGain();

    osc.connect(gain);
    gain.connect(audioCtx.destination);

    osc.type = "sine"; // soft ringtone style
    osc.frequency.value = freq;

    gain.gain.setValueAtTime(0.0001, audioCtx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.06, audioCtx.currentTime + 0.05);
    gain.gain.exponentialRampToValueAtTime(0.0001, audioCtx.currentTime + 0.25);

    osc.start();
    osc.stop(audioCtx.currentTime + 0.3);
}

// ringtone loop (calm, like phone notification)
function startSound(state) {

    if (alarmInterval) clearInterval(alarmInterval);

    let freq = 520;
    let interval = 2000;

    if (state === "WARNING") {
        freq = 600;
        interval = 1600;
    }

    if (state === "CRITICAL") {
        freq = 700;
        interval = 1200;
    }

    alarmInterval = setInterval(() => {
        playTone(freq);
        setTimeout(() => playTone(freq * 1.2), 200);
    }, interval);
}

// ================= ECG =================
function ecg(i) {

    let noise = (Math.random() - 0.5) * 8;
    let cycle = i % 100;

    let value = 0;

    if (cycle < 10) value = 10;
    else if (cycle < 20) value = -8;

    else if (cycle < 30) {

        value = 80;

        let now = Date.now();
        let diff = now - lastPeak;

        if (diff > 300 && diff < 2000) {
            bpm = Math.round(60000 / diff);
        }

        lastPeak = now;
    }

    else if (cycle < 40) value = -10;
    else value = 20;

    return value + noise;
}

// ================= RISK =================
function riskIndex(bpm) {

    if (!bpm) return 0;

    let score = 0;

    if (bpm < 60) score += 40;
    if (bpm > 100) score += 40;
    if (bpm < 40 || bpm > 130) score += 30;

    return Math.min(100, score);
}

// ================= ALARM =================
function alarmState(bpm) {

    if (!bpm) return "NORMAL";

    if (bpm < 40 || bpm > 130) return "CRITICAL";
    if (bpm < 60 || bpm > 100) return "WARNING";

    return "NORMAL";
}

// ================= GRID =================
function grid() {

    ctx.strokeStyle = "#003344";

    for (let i = 0; i < canvas.width; i += 20) {
        ctx.beginPath();
        ctx.moveTo(i, 0);
        ctx.lineTo(i, canvas.height);
        ctx.stroke();
    }

    for (let j = 0; j < canvas.height; j += 20) {
        ctx.beginPath();
        ctx.moveTo(0, j);
        ctx.lineTo(canvas.width, j);
        ctx.stroke();
    }
}

// ================= SPECTRUM =================
function drawSpectrum() {

    if (!sctx) return;

    sctx.fillStyle = "black";
    sctx.fillRect(0, 0, spec.width, spec.height);

    sctx.fillStyle = "#00e6ff";

    let data = signal.slice(-50);

    for (let i = 0; i < data.length; i++) {
        let h = Math.abs(data[i]) * 1.5;
        sctx.fillRect(i * 10, spec.height - h, 6, h);
    }
}

// ================= REAL PDF EXPORT =================
function exportPDF() {

    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();

    let risk = riskIndex(bpm);
    let alarm = lastStableAlarm;

    doc.setFontSize(16);
    doc.text("ECG PATIENT REPORT", 20, 20);

    doc.setFontSize(12);
    doc.text(`BPM: ${bpm || "N/A"}`, 20, 40);
    doc.text(`Risk Index: ${risk}`, 20, 50);
    doc.text(`Condition: ${alarm}`, 20, 60);

    doc.text("Interpretation:", 20, 80);

    let note = "";

    if (alarm === "NORMAL") note = "Stable heart activity detected.";
    if (alarm === "WARNING") note = "Irregular activity detected. Monitoring recommended.";
    if (alarm === "CRITICAL") note = "Critical condition detected. Immediate attention required.";

    doc.text(note, 20, 90);

    doc.text("Generated by ECG Biomedical Analyzer System", 20, 120);

    doc.save("ECG_Report.pdf");
}

// ================= DRAW =================
function draw() {

    if (!running) return;

    ctx.fillStyle = "black";
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    grid();

    let value = ecg(x);
    signal.push(value);

    if (signal.length > canvas.width) signal.shift();

    ctx.beginPath();
    ctx.strokeStyle = "#00ff66";

    for (let i = 0; i < signal.length; i++) {
        ctx.lineTo(i, canvas.height / 2 - signal[i]);
    }

    ctx.stroke();

    x++;

    // ================= LOGIC =================
    let risk = riskIndex(bpm);
    let rawAlarm = alarmState(bpm);

    // 1 MINUTE STABILITY RULE (~180 frames)
    if (rawAlarm !== lastStableAlarm) {
        changeCounter++;
        if (changeCounter > 180) {
            lastStableAlarm = rawAlarm;
            changeCounter = 0;
        }
    } else {
        changeCounter = 0;
    }

    let alarm = lastStableAlarm;

    history.push({ bpm, risk, alarm });

    if (history.length > 200) history.shift();

    // ================= UI =================
    document.getElementById("bpm").innerText = "BPM: " + (bpm || "--");
    document.getElementById("risk").innerText = "Risk Index: " + risk;

    let alarmEl = document.getElementById("alarm");
    alarmEl.innerText = "Alarm: " + alarm;

    alarmEl.style.color =
        alarm === "CRITICAL" ? "red" :
        alarm === "WARNING" ? "orange" : "#00ff88";

    // ================= SOUND =================
    startSound(alarm);

    drawSpectrum();

    requestAnimationFrame(draw);
}

// ================= CONTROLS =================
function toggle() {
    running = !running;

    if (running) {
        audioCtx.resume();
        draw();
    } else {
        clearInterval(alarmInterval);
    }
}

function switchPatient() {
    signal = [];
    bpm = 0;
    history = [];
}
